/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package db;

/**
 *
 * @author ricci.davide
 */
public class MenuForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuForm.class.getName());

    /**
     * Creates new form MenuForm
     */
    public MenuForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_ElencoGite = new javax.swing.JLabel();
        cmb_Gite = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txa_AlunniGite = new javax.swing.JTextArea();
        lbl_ElencoClassi = new javax.swing.JLabel();
        cmb_Classi = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        txa_ElencoClassi = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lbl_ElencoGite.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_ElencoGite.setText("ELENCO GITE");
        getContentPane().add(lbl_ElencoGite);
        lbl_ElencoGite.setBounds(20, 270, 200, 25);

        cmb_Gite.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gite" }));
        getContentPane().add(cmb_Gite);
        cmb_Gite.setBounds(20, 310, 130, 22);

        txa_AlunniGite.setEditable(false);
        txa_AlunniGite.setColumns(20);
        txa_AlunniGite.setRows(5);
        jScrollPane1.setViewportView(txa_AlunniGite);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 370, 240, 160);

        lbl_ElencoClassi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_ElencoClassi.setText("ELENCO CLASSI");
        getContentPane().add(lbl_ElencoClassi);
        lbl_ElencoClassi.setBounds(20, 0, 200, 25);

        cmb_Classi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Classi" }));
        getContentPane().add(cmb_Classi);
        cmb_Classi.setBounds(20, 40, 130, 22);

        txa_ElencoClassi.setEditable(false);
        txa_ElencoClassi.setColumns(20);
        txa_ElencoClassi.setRows(5);
        jScrollPane2.setViewportView(txa_ElencoClassi);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(20, 90, 240, 160);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmb_Classi;
    private javax.swing.JComboBox<String> cmb_Gite;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_ElencoClassi;
    private javax.swing.JLabel lbl_ElencoGite;
    private javax.swing.JTextArea txa_AlunniGite;
    private javax.swing.JTextArea txa_ElencoClassi;
    // End of variables declaration//GEN-END:variables
}
